In [17]:
import numpy as np
import pandas as pd

In [2]:
n_folds = 5
fold_scores = {}
fold_rankings = {}

In [4]:
for fold in range(n_folds):
    scores_name = "xgboost_scores_fold" + str(fold + 1)

    print("Loading scores for fold", fold, "...")
    # TODO: modify path
    scores = np.load('C:\\Users\\melan\\shared-folder\\RecSys\\RecSys-Competition\\scores_xgbfold\\' + scores_name + '.npy')

    # Assign the variable to the dictionary 
    fold_scores["scores_fold" + str(fold + 1)] = scores

Loading scores for fold 0 ...
Loading scores for fold 1 ...
Loading scores for fold 2 ...
Loading scores for fold 3 ...
Loading scores for fold 4 ...


In [5]:
for fold in range(n_folds):
    rankings_name = "xgboost_ranking_fold" + str(fold + 1)

    print("Loading rankings for fold", fold, "...")
    # TODO: modify path
    rankings = np.load('C:\\Users\\melan\\shared-folder\\RecSys\\RecSys-Competition\\scores_xgbfold\\' + rankings_name + '.npy')

    # Assign the variable to the dictionary 
    fold_rankings["rankings_fold" + str(fold + 1)] = rankings

Loading rankings for fold 0 ...
Loading rankings for fold 1 ...
Loading rankings for fold 2 ...
Loading rankings for fold 3 ...
Loading rankings for fold 4 ...


In [6]:
# Consistency check!
for fold in range(n_folds):
    rankings_name = "rankings_fold" + str(fold + 1)

    print(fold_rankings[rankings_name])

[[   2    4    1 ...   56   37   13]
 [ 101   36  403 ... 1630   68  257]
 [  47 1095   12 ...  210  416  422]
 ...
 [1411 1668  809 ...  163   24  138]
 [ 706 1124   32 ...   22  353    7]
 [ 733 4076 4082 ...   65 2237   14]]
[[   2    4    1 ...   56   37   13]
 [ 101   36  403 ... 1630   68  257]
 [  47 1095   12 ...  210  416  422]
 ...
 [1411 1668  809 ...  163   24  138]
 [ 706 1124   32 ...   22  353    7]
 [ 733 4076 4082 ...   65 2237   14]]
[[   2    4    1 ...   56   37   13]
 [ 101   36  403 ... 1630   68  257]
 [  47 1095   12 ...  210  416  422]
 ...
 [1411 1668  809 ...  163   24  138]
 [ 706 1124   32 ...   22  353    7]
 [ 733 4076 4082 ...   65 2237   14]]
[[   2    4    1 ...   56   37   13]
 [ 101   36  403 ... 1630   68  257]
 [  47 1095   12 ...  210  416  422]
 ...
 [1411 1668  809 ...  163   24  138]
 [ 706 1124   32 ...   22  353    7]
 [ 733 4076 4082 ...   65 2237   14]]
[[   2    4    1 ...   56   37   13]
 [ 101   36  403 ... 1630   68  257]
 [  47 1095   

In [7]:
items_selected = fold_rankings["rankings_fold1"]

In [14]:
fold_scores["scores_fold1"]

array([[ 0.01540205,  0.01540205,  0.01540205, ..., -0.05537045,
        -0.05537045, -0.05537045],
       [ 0.07448972,  0.07448972,  0.04006749, ..., -0.0167098 ,
        -0.04177722, -0.04141941],
       [ 0.04080619,  0.07921692,  0.04090384, ..., -0.07146298,
        -0.01310569, -0.00693211],
       ...,
       [ 0.10518736,  0.10518736,  0.0793831 , ..., -0.0341297 ,
        -0.0555185 , -0.0555185 ],
       [ 0.06123795,  0.07447964,  0.02516324, ..., -0.06457711,
        -0.07096634, -0.01548196],
       [ 0.04906843,  0.05921936,  0.04906843, ..., -0.00780599,
         0.04054333, -0.03654548]], dtype=float32)

In [8]:
# For each Recommender object we compute the scores and store them in scores_batch_array
scores_batch_array = np.array([fold_scores["scores_fold" + str(fold + 1)] for fold in range(n_folds)])

# Now compute the scores by  averaging over the scores of each fold
scores = np.average(scores_batch_array, axis= 0)

In [9]:
import tqdm

predictions = []

for user_id in range(len(scores)):
    scores_user = scores[user_id]
    items_user = items_selected[user_id]

    sorted_ranking = np.argsort(-scores_user)[:10]
    prediction = items_user[sorted_ranking]

    predictions.append(prediction) 

In [15]:
predictions

[array([ 2,  4,  1,  7,  3,  6,  8,  9, 15, 20], dtype=int64),
 array([  36,  101,  506,  123,  403,  515,  694, 1546, 1422,  592],
       dtype=int64),
 array([1095, 1522,   12,   47,   50,   11,  656,  949,   28,    4],
       dtype=int64),
 array([  59,  857,  259,  536,  956,  648,  584,  414, 1281,    9],
       dtype=int64),
 array([ 28, 249,  50,   5, 139,   7, 171, 146, 314, 145], dtype=int64),
 array([1570,    8,   77,  170,  471,  131, 1511,   59,  116,  270],
       dtype=int64),
 array([886,   9,  35,  88, 395, 103, 168, 104,  56,   6], dtype=int64),
 array([192,   2,   7,  88,   4,   1,   3,   9,  15, 284], dtype=int64),
 array([ 210,  443,  451,  722,  600,  480,    4, 3916, 1749,  778],
       dtype=int64),
 array([ 2,  7, 20, 16, 39, 26, 29, 36, 12, 58], dtype=int64),
 array([1816,  561, 1446, 1668, 2617, 2565, 2423, 3905,   67, 1767],
       dtype=int64),
 array([  40,   31,   58,   67,  955,   99,   34,  185, 1635,   32],
       dtype=int64),
 array([4704, 2582,  261,

In [19]:
predictions_list = []
predictions_list = predictions

prediction_df = pd.read_csv('C:\\Users\\melan\\shared-folder\\RecSys\\RecSys-Competition\\data_target_users_test.csv', sep= ",",
                            header=0, 
                            dtype={0:int},
                            engine='python')
users = np.array(prediction_df['user_id'])
predictions_list = [predictions_list[i] for i in users]
truncated_recommendations = [inner_list[:10] for inner_list in predictions_list]
prediction_df['item_list'] = truncated_recommendations
def transform_items_to_string(item_list):
    return ' '.join(map(str, item_list))

prediction_df['item_list'] = prediction_df['item_list'].apply(transform_items_to_string)
print(prediction_df.head(10))
prediction_df.to_csv('submission.csv',index=False)

   user_id                                       item_list
0        1        36 101 506 123 403 515 694 1546 1422 592
1        2              1095 1522 12 47 50 11 656 949 28 4
2        3           59 857 259 536 956 648 584 414 1281 9
3        4               28 249 50 5 139 7 171 146 314 145
4        5           1570 8 77 170 471 131 1511 59 116 270
5        6                886 9 35 88 395 103 168 104 56 6
6        8         210 443 451 722 600 480 4 3916 1749 778
7        9                     2 7 20 16 39 26 29 36 12 58
8       10  1816 561 1446 1668 2617 2565 2423 3905 67 1767
9       11               40 31 58 67 955 99 34 185 1635 32
